apiVersion: v1
kind: Secret
metadata:
  name: {{ template "event-hubs-web-stream.fullname" . }}
  labels:
    app: {{ template "event-hubs-web-stream.name" . }}
    chart: {{ template "event-hubs-web-stream.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connectionString: {{ required "ERROR: add \"--set connectionString=<hub_connection_string>\"." .Values.connectionString | b64enc | quote }}
